export const PANEL_LOGIN = 'PANEL_LOGIN';
export const PANEL_REGISTER = 'PANEL_REGISTER';

export const LOGGING = 'LOGGING';
export const LOGGING_PENDING = 'LOGGING_PENDING';
export const LOGGING_FULFILLED = 'LOGGING_FULFILLED';
export const LOGGING_REJECTED = 'LOGGING_REJECTED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';

export const REGISTER = 'REGISTER';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';